server:
    port: 8761

eureka:
    instance:
        hostname: localhost
        prefer-ip-address: true
    client:
        registerWithEureka: false   #属性表示是否将自己注册到Eureka Server， 默认为true。 由于当前应用就是Eureka Server， 因此设为 false；
        fetchRegistry: false        #表示是否从Eureka Server获取注册信息，默认为true。 如果这是一个单点的 Eureka Server，不需要同步其他节点的数据，可以设为false。
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
    level.com.netflix.eureka: OFF
    level.com.netflix.discovery: OFF


spring:
    application:
        name: spring-cloud-eureka-server
    boot:
        admin:
            client:
                url: http://127.0.0.1:8000                      ## 指向 spring boot admin server
                username: admin
                password: admin
#                instance:
#                    service-base-url:  http://127.0.0.1:8080    ## 通过 war 方式部署的时候，需要指定被注册的app 的访问 url

##actuator 的功能开放
management:
    endpoints:
        web:
            exposure:
                include: "*"
##actuator 配置结束
