spring:
    application:
        name: feign-client

server:
    port: 8765

eureka:
    client:
        serviceUrl:
            defaultZone: http://119.3.25.179:8761/eureka/


#解决 在 spring boot 2.0 下 hystrix.stream 404的错误
management:
    endpoints:
        web:
            exposure:
                include: '*'