server:
    port: 8765

spring:
    application:
        name: feign-client-with-resilience4j-circuitbreaker
    security:
        user:
            name: admin
            password: admin
    boot:
        admin:
            client:
                url: http://127.0.0.1:8000                      ## 指向 spring boot admin server
                username: admin
                password: admin
#                instance:
#                    service-base-url:  http://127.0.0.1:8080    ## 通过 war 方式部署的时候，需要指定被注册的app 的访问 url

resilience4j.circuitbreaker:
    backends:
        backendA:
            ringBufferSizeInClosedState: 5
            ringBufferSizeInHalfOpenState: 3
            waitInterval: 5000
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
        fetchRegistry: true

management:
    endpoints:
        web:
            exposure:
                include: '*'

logging:
    config: classpath:logback-${spring.profiles.active}.xml