server:
    port: 8765

spring:
    application:
        name: feign-client
    security:
        user:
            name: admin
            password: admin
    boot:
        admin:
            client:
                url: http://127.0.0.1:8000                      ## 指向 spring boot admin server
                username: admin
                password: admin
#                instance:
#                    service-base-url:  http://127.0.0.1:8080    ## 通过 war 方式部署的时候，需要指定被注册的app 的访问 url
    redis:
        host: 119.3.24.23
        password: 1qaz369*
        port: 16379
        database: 3
        ## 连接超时时间（15秒）
        timeout: 15s
        jedis:
            pool:
                ## 连接池最大连接数（使用负值表示没有限制）
                max-active: 100
                ## 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms
                ## 连接池中的最大空闲连接
                max-idle: 8
                ## 连接池中的最小空闲连接
                min-idle: 0

eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
        fetchRegistry: true

management:
    endpoints:
        web:
            exposure:
                include: '*'

logging:
    config: classpath:logback-${spring.profiles.active}.xml